//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public int MaGioHang { get; set; }
        public string MaSP { get; set; }
        public int SoLuong { get; set; }
        public double GiaTien { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
