//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Admin { get; set; }
        public string AnhNV { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
    }
}
